apiVersion: apps/v1
kind: Deployment
metadata:
  name: gal-alon-nginx-deployment
  namespace: app-ga
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        nodegroup: app
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image }}:nginx-image-{{ .Values.imageVersion }}"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
