apiVersion: apps/v1
kind: Deployment
metadata:
  name: gal-alon-wsgi-deployment
  namespace: app-ga
  labels:
    app: my-app
spec:
  replicas: {{ .Values.wsgi.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        nodegroup: app
      containers:
      - name: wsgi
        image: "{{ .Values.wsgi.image }}:django-image-{{ .Values.imageVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
          name: metrics
